import Testing
import Foundation
@testable import PasteboardKit

final class FakePasteboard: PasteboardReading, @unchecked Sendable {
    var changeCount = 0
    var types: [String] = []
    var text: String?
    var image: Data?
    var files: [String]?
    func string() -> String? { text }
    func imageData() -> Data? { image }
    func fileURLStrings() -> [String]? { files }

    func put(text: String, types: [String] = ["public.utf8-plain-text"]) {
        self.text = text; self.image = nil; self.files = nil
        self.types = types; changeCount += 1
    }
}

// ClipCapture artık @MainActor (fix round 1, HotKeyCenter'daki aynı gerekçe);
// bu dosyadaki her test o yüzden @MainActor işaretli.
@MainActor
private func capture(_ pb: FakePasteboard, blocked: Set<String> = []) -> ClipCapture {
    ClipCapture(pasteboard: pb, policy: CapturePolicy(blockedBundleIDs: blocked))
}

@MainActor @Test func firstPollAfterACopyReturnsTheClip() {
    let pb = FakePasteboard(); pb.put(text: "merhaba")
    #expect(capture(pb).poll(frontmostBundleID: nil)?.text == "merhaba")
}

@MainActor @Test func pollingWithoutAChangeReturnsNothing() {
    // Yoklama saniyede iki kez çalışıyor; değişmeyen panoyu tekrar tekrar
    // kaydetmek geçmişi çöple doldururdu.
    let pb = FakePasteboard(); pb.put(text: "merhaba")
    let c = capture(pb)
    _ = c.poll(frontmostBundleID: nil)
    #expect(c.poll(frontmostBundleID: nil) == nil)
}

@MainActor @Test func concealedContentIsNeverCaptured() {
    // Şifre yöneticileri panoya bu tipi koyar. Kaydetmek gizlilik ihlali olur.
    let pb = FakePasteboard()
    pb.put(text: "hunter2", types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"])
    #expect(capture(pb).poll(frontmostBundleID: nil) == nil)
}

@MainActor @Test func transientAndAutoGeneratedContentIsSkippedToo() {
    let pb = FakePasteboard()
    pb.put(text: "geçici", types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"])
    #expect(capture(pb).poll(frontmostBundleID: nil) == nil)
    pb.put(text: "üretilmiş", types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"])
    #expect(capture(pb).poll(frontmostBundleID: nil) == nil)
}

@MainActor @Test func copiesFromBlockedAppsAreDropped() {
    let pb = FakePasteboard(); pb.put(text: "parola")
    #expect(capture(pb, blocked: ["com.1password.1password"])
        .poll(frontmostBundleID: "com.1password.1password") == nil)
}

@MainActor @Test func updatingPolicyAfterConstructionBlocksSubsequentPolls() {
    // Ayarlar penceresi kara listeyi uygulama çalışırken değiştirebilir
    // (Task 13). `policy` bir `let` olsaydı bu asla gerçekleşmezdi ve kullanıcı
    // az önce engellediği bir uygulamadan kopyalanmaya devam ederdi.
    let pb = FakePasteboard(); pb.put(text: "parola")
    let c = capture(pb)
    c.updatePolicy(CapturePolicy(blockedBundleIDs: ["com.1password.1password"]))
    #expect(c.poll(frontmostBundleID: "com.1password.1password") == nil)
}

@MainActor @Test func updatingPolicyCanAlsoUnblockAnApp() {
    let pb = FakePasteboard(); pb.put(text: "merhaba")
    let c = capture(pb, blocked: ["com.example.app"])
    c.updatePolicy(CapturePolicy())
    #expect(c.poll(frontmostBundleID: "com.example.app")?.text == "merhaba")
}

@MainActor @Test func urlsAreRecognisedAsLinks() {
    let pb = FakePasteboard(); pb.put(text: "https://girltalk.social")
    #expect(capture(pb).poll(frontmostBundleID: nil)?.kind == .link)
}

@MainActor @Test func plainWordsAreNotLinks() {
    let pb = FakePasteboard(); pb.put(text: "girltalk sosyal")
    #expect(capture(pb).poll(frontmostBundleID: nil)?.kind == .text)
}

@MainActor @Test func imageDataBecomesAnImageClip() {
    let pb = FakePasteboard()
    pb.image = Data([0x89, 0x50, 0x4E, 0x47]); pb.text = nil
    pb.types = ["public.png"]; pb.changeCount += 1
    let clip = capture(pb).poll(frontmostBundleID: nil)
    #expect(clip?.kind == .image)
    #expect(clip?.imageData != nil)
}

@MainActor @Test func emptyOrWhitespaceOnlyTextIsIgnored() {
    let pb = FakePasteboard(); pb.put(text: "   \n  ")
    #expect(capture(pb).poll(frontmostBundleID: nil) == nil)
}

@MainActor @Test func identicalContentHashesTheSameSoTheStoreCanMerge() {
    let pb = FakePasteboard()
    pb.put(text: "aynı")
    let first = capture(pb).poll(frontmostBundleID: nil)
    pb.put(text: "aynı")
    let second = capture(pb).poll(frontmostBundleID: nil)
    #expect(first?.contentHash == second?.contentHash)
}

@MainActor @Test func fileAndTextClipsWithTheSameStringHashDifferently() {
    // Bir dosya yolu ("/Users/x/notes.txt") aynı zamanda geçerli bir metin
    // kopyası olabilir. Kind'ı hash'e katmazsak Store.upsert bu ikisini
    // aynı satırda birleştirir ve biri sessizce yanlış türde görünür.
    let filePB = FakePasteboard()
    filePB.files = ["/Users/x/notes.txt"]
    filePB.types = ["public.file-url"]
    filePB.changeCount += 1
    let fileClip = capture(filePB).poll(frontmostBundleID: nil)

    let textPB = FakePasteboard()
    textPB.put(text: "/Users/x/notes.txt")
    let textClip = capture(textPB).poll(frontmostBundleID: nil)

    #expect(fileClip?.kind == .file)
    #expect(textClip?.kind == .text)
    #expect(fileClip?.contentHash != textClip?.contentHash)
}
