import Foundation
import CryptoKit

public enum CapturedKind: String, Sendable { case text, image, link, file }

public struct CapturedClip: Sendable, Equatable {
    public let kind: CapturedKind
    public let text: String?
    public let imageData: Data?
    public let contentHash: String
}

public struct CapturePolicy: Sendable {
    public var blockedBundleIDs: Set<String>
    public init(blockedBundleIDs: Set<String> = []) {
        self.blockedBundleIDs = blockedBundleIDs
    }
}

public final class ClipCapture {
    /// Diğer uygulamaların "bunu kaydetme" demek için kullandığı iş birliği
    /// tipleri. nspasteboard.org'daki gayriresmî ama yaygın sözleşme.
    static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let pasteboard: PasteboardReading
    private let policy: CapturePolicy
    private var lastChangeCount: Int?

    public init(pasteboard: PasteboardReading, policy: CapturePolicy) {
        self.pasteboard = pasteboard
        self.policy = policy
    }

    public func poll(frontmostBundleID: String?) -> CapturedClip? {
        let count = pasteboard.changeCount
        defer { lastChangeCount = count }
        guard count != lastChangeCount else { return nil }
        guard Set(pasteboard.types).isDisjoint(with: Self.skipTypes) else { return nil }
        if let id = frontmostBundleID, policy.blockedBundleIDs.contains(id) { return nil }

        if let data = pasteboard.imageData(), !data.isEmpty {
            return CapturedClip(kind: .image, text: nil, imageData: data,
                                contentHash: Self.hash(.image, data))
        }
        if let paths = pasteboard.fileURLStrings(), !paths.isEmpty {
            let joined = paths.joined(separator: "\n")
            return CapturedClip(kind: .file, text: joined, imageData: nil,
                                contentHash: Self.hash(.file, Data(joined.utf8)))
        }
        guard let text = pasteboard.string(),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        let kind: CapturedKind = Self.isLink(text) ? .link : .text
        return CapturedClip(kind: kind, text: text,
                            imageData: nil, contentHash: Self.hash(kind, Data(text.utf8)))
    }

    static func isLink(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(" "), let url = URL(string: trimmed) else { return false }
        return url.scheme == "http" || url.scheme == "https"
    }

    /// Kind, hash'e dahil edilir: ham baytları aynı olan ama farklı türden içerik
    /// (ör. bir dosya yolu string'i == bir metin kopyası) aynı hash'e düşüp
    /// Store.upsert'te sessizce birleşmesin.
    static func hash(_ kind: CapturedKind, _ data: Data) -> String {
        var payload = Data((kind.rawValue + ":").utf8)
        payload.append(data)
        return SHA256.hash(data: payload).map { String(format: "%02x", $0) }.joined()
    }
}
