import Foundation
import CryptoKit

public enum CapturedKind: String, Sendable { case text, image, link, file }

public struct CapturedClip: Sendable, Equatable {
    public let kind: CapturedKind
    public let text: String?
    public let imageData: Data?
    public let contentHash: String
}

public struct CapturePolicy: Sendable {
    public var blockedBundleIDs: Set<String>
    public init(blockedBundleIDs: Set<String> = []) {
        self.blockedBundleIDs = blockedBundleIDs
    }
}

/// @MainActor: `policy` artık `var` ve `updatePolicy(_:)` ile ayarlar
/// penceresinden, `poll(frontmostBundleID:)` ise `CaptureCoordinator`'ın
/// zamanlayıcısından okunuyor. İkisinin de "aynı iş parçacığında çalışır"
/// sözleşmesine güvenip bırakmak HotKeyCenter'ın aynı sınıfta yaşadığı
/// sorunu tekrarlardı: hiçbir şey `updatePolicy`'nin arka planda
/// çağrılmasını engellemiyordu. Tip artık bunu derleyicide zorluyor —
/// bkz. HotKeyCenter'daki aynı gerekçe.
@MainActor
public final class ClipCapture {
    /// Diğer uygulamaların "bunu kaydetme" demek için kullandığı iş birliği
    /// tipleri. nspasteboard.org'daki gayriresmî ama yaygın sözleşme.
    static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private let pasteboard: PasteboardReading
    private var policy: CapturePolicy
    private var lastChangeCount: Int?

    public init(pasteboard: PasteboardReading, policy: CapturePolicy) {
        self.pasteboard = pasteboard
        self.policy = policy
    }

    /// Ayarlar penceresinden kara liste değişince çağrılır. `policy` bir `let`
    /// olsaydı çalışan yakalama, kullanıcı bir uygulamayı az önce engellediği
    /// halde ondan kopyalamayı sürdürürdü — ayarlar arayüzü yalan söylemiş
    /// olurdu (bkz. Task 8 incelemesi, Task 13'e taşınan bulgu). Yoklama
    /// döngüsünü yeniden kurmadan (zamanlayıcıyı tekrar başlatmadan) canlı
    /// güncelleme yapmanın en dar yolu bu.
    public func updatePolicy(_ policy: CapturePolicy) {
        self.policy = policy
    }

    /// `PasteEngine`in kendi yazdığı bir pano değişikliğini işaretler
    /// (I2): bir sonraki `poll` bu tam `changeCount`u gördüğünde onu
    /// "değişiklik yok" sayıp atlar — `lastChangeCount`in zaten yaptığı
    /// karşılaştırmaya, dışarıdan bilinen bir değeri erkenden yerleştirmekten
    /// başka bir şey değil. Yalnızca BU değişiklik atlanır: hemen ardından
    /// gelen gerçek bir kullanıcı kopyalaması panonun changeCount'unu
    /// yeniden ilerletir, bir sonraki `poll` onu normal şekilde yakalar.
    /// `ClipCapture` bunu kimin çağırdığını bilmiyor — `PasteEngine`i hiç
    /// içe aktarmıyor, iki modül birbirinden habersiz kalıyor (bkz.
    /// `PasteEngine.onWrite`, bağlayan taraf `AppDelegate`).
    public func suppressChangeCount(_ changeCount: Int) {
        lastChangeCount = changeCount
    }

    public func poll(frontmostBundleID: String?) -> CapturedClip? {
        let count = pasteboard.changeCount
        defer { lastChangeCount = count }
        guard count != lastChangeCount else { return nil }
        guard Set(pasteboard.types).isDisjoint(with: Self.skipTypes) else { return nil }
        if let id = frontmostBundleID, policy.blockedBundleIDs.contains(id) { return nil }

        if let data = pasteboard.imageData(), !data.isEmpty {
            return CapturedClip(kind: .image, text: nil, imageData: data,
                                contentHash: Self.hash(.image, data))
        }
        // Web bağlantısı, dosya kontrolünden ÖNCE ve NSURL okuyucusu
        // üzerinden denetlenir: bu, tam URL metnini (sorgu+parça dahil)
        // `pasteboard.string()`in ilgili tipi hiç yazmadığı uygulamalarda
        // bile garantiler ve genel metin sezgisine (isLink) muhtaç bırakmaz
        // (C1). fileURLStrings() artık yalnızca gerçek file:// URL'lerini
        // döndürdüğü için (bkz. PasteboardReading), buradan geçen bir web
        // bağlantısı asla file dalına düşmez.
        if let link = pasteboard.webURLString(), !link.isEmpty {
            return CapturedClip(kind: .link, text: link, imageData: nil,
                                contentHash: Self.hash(.link, Data(link.utf8)))
        }
        if let paths = pasteboard.fileURLStrings(), !paths.isEmpty {
            let joined = paths.joined(separator: "\n")
            return CapturedClip(kind: .file, text: joined, imageData: nil,
                                contentHash: Self.hash(.file, Data(joined.utf8)))
        }
        guard let text = pasteboard.string(),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        let kind: CapturedKind = Self.isLink(text) ? .link : .text
        return CapturedClip(kind: kind, text: text,
                            imageData: nil, contentHash: Self.hash(kind, Data(text.utf8)))
    }

    static func isLink(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(" "), let url = URL(string: trimmed) else { return false }
        return url.scheme == "http" || url.scheme == "https"
    }

    /// Kind, hash'e dahil edilir: ham baytları aynı olan ama farklı türden içerik
    /// (ör. bir dosya yolu string'i == bir metin kopyası) aynı hash'e düşüp
    /// Store.upsert'te sessizce birleşmesin.
    static func hash(_ kind: CapturedKind, _ data: Data) -> String {
        var payload = Data((kind.rawValue + ":").utf8)
        payload.append(data)
        return SHA256.hash(data: payload).map { String(format: "%02x", $0) }.joined()
    }
}
